language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
      dist: xenial

    - python: 3.6
      env: TOXENV=docs

install:
  - travis_retry pip install tox

script:
  - travis_retry tox

cache:
  directories:
    - $HOME/.cache/pip
